controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.1
  max_vel_theta: 0.7
  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 1.0

  vx_samples: 5.0
  vtheta_samples: 10.0

  meter_scoring: true

  holonomic_robot: false
